name: 'pr-comments'
description: 'Adds PR changes as comment'

# Define your inputs here.
inputs:
  owner:
    description: 'the owner of repo (ueser or org)'
    required: true
  repo:
    description: 'the repo name'
    required: true
  pr_number:
    description: 'the number of the pull request'
    required: true
  token:
    description: 'the token to access to the GitHub API'
    required: true
runs:
  using: 'node20'
  main: dist/index.js
